#!/bin/bash

# Download plug.vim script needed to install neovim plugins
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Upgrade pip version
python3 -m pip install --upgrade pip

# Install Python formatting tools in home directory
pip install --user black isort

# Install meson and ninja
pip install --user meson ninja

# Update rustup
rustup self update

# Update Rust stable version
rustup update stable

# Install rustfmt and clippy
rustup component add rustfmt clippy

# Install hyperfine
cargo install hyperfine

# Add favorite apps to dock
gsettings set org.gnome.shell favorite-apps "[
'org.gnome.gedit.desktop',
'org.gnome.Nautilus.desktop',
'firefox.desktop',
'com.alacritty.Alacritty.desktop',
'org.gnome.Evince.desktop',
'thunderbird.desktop',
'telegram.desktop',
'gnome-system-monitor.desktop'
]"
