#!/usr/bin/env python3

# Comment out the programs you do not want to install!

import argparse
import collections
import subprocess
import typing as T

# Define a namedtuple to describe a program
Program = collections.namedtuple(
    "Program",
    field_names=["command", "is_snap", "run_script"],
    defaults=["", False, None],
)

# Common programs between the two operating systems
PROGRAMS = [
    # apt packages
    Program("build-essential"),  # build tools
    Program("curl"),  # curl
    Program("fish"),  # fish shell
    Program("mpv"),  # mpv player
    Program("neovim"),  # neovim editor
    Program("npm"),  # npm
    Program("python3-pip"),  # pip3
    Program("python3-venv"),  # venv used by black
    Program(
        run_script=[
            'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
        ]
    ),  # rust
    Program("snapd"),  # snap package manager
    Program("stow"),  # stow
    Program("thunderbird"),  # thunderbird
    Program("tmux"),  # tmux terminal multiplexer
    # Snap packages
    Program("alacritty", is_snap=True),  # alacritty
    Program("telegram-desktop", is_snap=True),  # telegram-desktop
    Program("vlc", is_snap=True),  # vlc
]

# Install programs for a determined operating system
def install_programs(
    use_sudo: T.List[str], install_command: T.List[str], programs: T.List["Program"]
) -> None:
    for program in programs:
        # Check whether a program needs to be installed through snap
        if program[1]:
            use_command = ["snap", "install"]
        else:
            use_command = install_command

        # Check whether a program needs to be installed through a script
        if program[2]:
            for command in program[2]:
                ps = subprocess.Popen(
                    command,
                    shell=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                )
                output = ps.communicate()[0]
                print(output.decode())
        else:
            subprocess.run(use_sudo + use_command + program[0].split())


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="install",
        description="This tool installs my own software on different "
        "Linux distributions (Ubuntu)",
    )

    # Get arguments
    args = parser.parse_args()

    # Use sudo to install programs
    use_sudo = ["sudo"]

    # Avoid stale index
    subprocess.run(use_sudo + ["apt-get", "update"])

    install_command = ["apt-get", "-y", "install"]

    # Install common programs
    install_programs(use_sudo, install_command, PROGRAMS)

if __name__ == "__main__":
    main()
