#!/usr/bin/env python3

import os
import subprocess
import sys
from pathlib import Path
import typing as T

dotfiles_path = Path(__file__).parent


def is_package(path: Path) -> bool:
    """Filter out paths that don't represent packages."""
    if not path.is_dir():
        return False
    elif path.name.startswith("."):
        return False
    return True


def stow(
    package_names: T.List[str],
    dir: Path = dotfiles_path,
    target: Path = Path.home(),
) -> int:

    cmd = [
        "stow",
        f"--dir={dir!s}",
        f"--target={target!s}",
        *package_names,
    ]

    return subprocess.call(cmd, stdout=sys.stdout, stderr=sys.stderr)


def main() -> int:
    # -n, --no
    # --adopt
    # -v, --verbose
    # -S, --stow
    # -R, --restow
    # -D, --delete

    exclude_packages = set()
    provided_package_names = set()
    for arg in sys.argv[1:]:
        provided_package_names.add(arg)

    available_package_paths = {
        path for path in dotfiles_path.glob("*") if is_package(path)
    }
    available_package_names = {path.name for path in available_package_paths}
    package_names = provided_package_names & available_package_names

    if not package_names or len(package_names) == len(available_package_names):
        package_names = available_package_names - exclude_packages

    result = stow(package_names)

    return result


if __name__ == "__main__":
    sys.exit(main())
