#!/bin/bash

# Bytehound memory profiler

INPUT=$@
[ -z "$INPUT" ] && exit

export MEMORY_PROFILER_LOG=warn
sudo LD_PRELOAD=$HOME/.cargo/bin/libbytehound.so $INPUT
bytehound server memory-profiling_*.dat
