#!/bin/bash

set -ex

# Install FFmpeg dependencies
sudo apt install nasm
sudo apt install libass-dev
sudo apt install libfdk-aac-dev
sudo apt install libmp3lame-dev
sudo apt install libopus-dev
sudo apt install libvorbis-dev
sudo apt install libaom-dev
sudo apt install libvpx-dev
sudo apt install libx264-dev
sudo apt install libx265-dev

# Run FFmpeg configure script
./configure \
    --disable-debug \
    --disable-doc \
    --disable-libdrm \
    --disable-cuda \
    --enable-fontconfig \
    --enable-gpl \
    --enable-libass \
    --enable-libfdk-aac \
    --enable-libfreetype \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libaom \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-shared \
    --enable-version3 \
    --enable-nonfree

# Compile FFmpeg
make -j4

# Install FFmpeg
sudo make install
