#!/bin/bash

[ -z $1 ] || cd $1

# Close a prior session
tmux kill-session -t dev > /dev/null 2>&1

tmux new-session -s dev -d
tmux rename-window dev
tmux new-window
tmux rename-window build
tmux new-window
tmux rename-window run
tmux select-window -t 1
tmux attach -t dev
