#!/bin/sh

[ -z $1 ] || cd $1

while read -r name
do
    [ -d .git ] && git config --local user.name "$name"
done <~/name.txt

tmux new-session -d
tmux split-window -h
tmux split-window -v
[ -z $2 ] || tmux rename-window $2
tmux select-pane -t 1
tmux -2 attach-session -d
