#!/bin/bash

# Show installed nvidia packages
dpkg -l | grep -i nvidia

# Purge all nvidia drivers
sudo apt-get remove --purge '*nvidia*'

# Remove package index leftovers
sudo rm -rf /etc/apt/sources.list.d/cuda*
