#!/bin/bash

[ -z $1 ] || cd $1

while read -r name
do
    [ -d .git ] && git config --local user.name "$name"
done <~/name.txt

# Close a prior session
tmux kill-session -t $2 > /dev/null 2>&1

tmux new-session -s $2 -d
tmux rename-window $2
tmux new-window
tmux rename-window build
tmux new-window
tmux rename-window run
tmux select-window -t 1
tmux attach -t $2
